### ISSUE TITLE
这个怎么用呢？

### ISSUE THREAD

**Issue by wayss000** [weiqiujuan/todoList-electron#1]
:smile:

**Comment by weiqiujuan** [comment]
还没有开发完，yarn i，yarn run dev有些功能依赖后台-------- 原始邮件 --------主题：[weiqiujuan/todoList-electron] 这个怎么用呢？ (#1)发件人：Wayss 收件人：weiqiujuan/todoList-electron 抄送：Subscribed 😄



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/weiqiujuan/todoList-electron","title":"weiqiujuan/todoList-electron","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/weiqiujuan/todoList-electron"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个怎么用呢？ (#1)"}],"action":{"name":"View Issue","url":"https://github.com/weiqiujuan/todoList-electron/issues/1"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/weiqiujuan/todoList-electron/issues/1",

"url": "https://github.com/weiqiujuan/todoList-electron/issues/1",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by wayss000** [comment]
> 还没有开发完，yarn i，yarn run dev有些功能依赖后台-------- 原始邮件 --------主题：[weiqiujuan/todoList-electron] 这个怎么用呢？ (#1)发件人：Wayss 收件人：weiqiujuan/todoList-electron 抄送：Subscribed  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/weiqiujuan/todoList-electron","title":"weiqiujuan/todoList-electron","subtitle":"GitHub repository","main_image_url":"[https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/weiqiujuan/todoList-electron"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个怎么用呢？](https://github.com/weiqiujuan/todoList-electron%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22DESCRIPTION%22,%22message%22:%22%E8%BF%99%E4%B8%AA%E6%80%8E%E4%B9%88%E7%94%A8%E5%91%A2%EF%BC%9F) (#1)"}],"action":{"name":"View Issue","url":"#1"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#1", "url": "#1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by wayss000** [comment]
你回复的是什么呀 :sweat_smile:
